import Navbar from '@/components/Layouts/Navbar';
import Providers from '@/components/Providers';
import ReactQueryProviders from '@/lib/Provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <Providers>
          <ReactQueryProviders>{children}</ReactQueryProviders>
        </Providers>
      </body>
    </html>
  );
}
